export const languages = {
    "C++":        { extension: "cpp"   },
    "Java":       { extension: "java"  },
    "Python3":    { extension: "py"    },
    "Python":     { extension: "py"    },
    "JavaScript": { extension: "js"    },
    "TypeScript": { extension: "ts"    },
    "C#":         { extension: "cs"    },
    "C":          { extension: "c"     },
    "Go":         { extension: "go"    },
    "Kotlin":     { extension: "kt"    },
    "Swift":      { extension: "swift" },
    "Rust":       { extension: "rs"    },
    "Ruby":       { extension: "rb"    },
    "PHP":        { extension: "php"   },
    "Dart":       { extension: "dart"  },
    "Scala":      { extension: "scala" },
    "Elixir":     { extension: "ex"    },
    "Erlang":     { extension: "erl"   },
    "Racket":     { extension: "rkt"   },
  };
  